#!/usr/bin/env perl

# The input arguments to this script are:
# $ARGV[0] = location of Xyce binary
# $ARGV[1] = location of xyce_verify.pl script
# $ARGV[2] = location of compare script  (This is NEVER used and can be ignored)
# $ARGV[3] = location of circuit file to test
# $ARGV[4] = location of gold standard prn file

# This test case runs a simple biased transistor and computes the
# sensitivities with respect to a few model variables.
#
# A second netlist, in which the sensitivities are generated by finite
# differencing between perturbed copies of the circuit, is also run.  The
# analytic sensitivities from the first netlist are compared to the
# sensitivities from the second.

$XYCE=$ARGV[0];
$XYCE_VERIFY=$ARGV[1];
#$CIRFILE=$ARGV[3]; 

$CIR1="bug669a.cir";
$CIR2="bug669b.cir";

`rm -f $CIR1*prn* $CIR1*.out $CIR2*prn* $CIR2*.out $CIR1.err $CIR2.err`;

# Run the test circuit
$CMD="$XYCE $CIR1 > $CIR1.out 2> $CIR1.err";
if (system($CMD) != 0)
{
    print "Xyce EXITED WITH ERROR! on $CIR1\n";
    $xyceexit=1;
}
else
{
    if (-z "$CIR1.err" ) {`rm -f $CIR1.err`;}
}

if (defined ($xyceexit)) {print "Exit code = 10\n"; exit 10;}

if ( ! -f "$CIR1.SENS.prn")
{
    print STDERR "$CIR1.SENS.prn not created\n";
    print "Exit code = 14\n";
    exit 14;
}

# Run the gold standard circuit
$CMD="$XYCE $CIR2 > $CIR2.out 2> $CIR2.err";
if (system($CMD) != 0)
{
    print "Xyce EXITED WITH ERROR! on $CIR2\n";
    $xyceexit=1;
}
else
{
    if (-z "$CIR2.err" ) {`rm -f $CIR2.err`;}
}

if (defined ($xyceexit)) {print "Exit code = 10\n"; exit 10;}

if ( ! -f "$CIR2.SENS.prn")
{
    print STDERR "$CIR2.SENS.prn not created\n";
    print "Exit code = 14\n";
    exit 14;
}

# The gold standard circuit .prn file has a slightly different headers than the analytic 
# .SENS.prn, which will cause xyce_verify to complain vigorously and exit
# due to the header mismatch if used directly.  So we will simply copy the
# .SENS.prn header of the analytic file into the gold standard, and use that
# modified version for comparison.  

$HEADER1=`head -1 $CIR1.SENS.prn`;
chomp $HEADER1;
$SEDCMD="sed '1 s-^.*\$-".$HEADER1."-g'";

`$SEDCMD $CIR2.SENS.prn > $CIR2.SENS2.prn`;

$CMD="$XYCE_VERIFY --printline=sens $CIR1 $CIR2.SENS2.prn  $CIR1.SENS.prn > $CIR1.prn.out 2> $CIR1.prn.err";

if (system($CMD) != 0)
{
    print STDERR "Comparison between analytic and gold standard sensitivities failed, see $CIR1.prn.err for detail.\n";
    print "Exit code = 2\n";
    exit 2;
}
else
{
    print "Exit code = 0\n";
    exit 0;
}
