Certification_Tests/A a.cir
Certification_Tests/Bserialnightly b.cir
Certification_Tests/Cparallelnightly c.cir
Certification_Tests/Dserialparallelweekly d.cir
exclude include.cir
exclude includelocal.cir
klu klu.cir
NoTags serialnightly.cir
NoTags serialweekly.cir
OUOTests/Certification_Tests/E e.cir
OUOTests/Certification_Tests/F f.cir
OUOTests/Certification_Tests/G g.cir
OUOTests/Certification_Tests/H h.cir
OUOTests/radAnightly radA.cir
OUOTests/radBweekly radB.cir
OUOTests/stress_tests/EE ee.cir
OUOTests/stress_tests/FF ff.cir
OUOTests/stress_tests/GG gg.cir
OUOTests/stress_tests/HH hh.cir
SerialAndParallel parallel.cir
SerialAndParallel serialandparallel.cir
SerialAndParallel serial.cir
stress_tests/DD dd.cir
valgrind valgrind.cir
